tasks:
  - init: |
      python -m virtualenv venv
    command: |
      source venv/bin/activate
      pip install -r requirements.txt
      jupyter notebook --config=jupyter_notebook_config.py notebooks

ports:
  - port: 8888
    onOpen: open-browser
